"""Add shared column to AnalysisHistory

Revision ID: dfb4e5c4d023
Revises: 8d97a22ead54
Create Date: 2026-01-19 15:50:16.386076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb4e5c4d023'
down_revision = '8d97a22ead54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.drop_column('shared')

    # ### end Alembic commands ###
