"""Add csv_file column to AnalysisHistory

Revision ID: f433427acf1f
Revises: dfb4e5c4d023
Create Date: 2026-01-19 22:19:14.048054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f433427acf1f'
down_revision = 'dfb4e5c4d023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csv_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_history', schema=None) as batch_op:
        batch_op.drop_column('csv_file')

    # ### end Alembic commands ###
